# Generated by Django 5.2.11 on 2026-02-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_billingcycle_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='cancellation_url',
            field=models.URLField(blank=True, help_text='Direct page where users can cancel with this provider.'),
        ),
    ]
