# Generated by Django 5.2.11 on 2026-02-20 18:10

from django.db import migrations


PREDEFINED_PROVIDERS = [
    {
        "name": "Netflix",
        "category": "Streaming",
        "website": "https://www.netflix.com/",
        "cancellation_url": "https://www.netflix.com/cancelplan",
    },
    {
        "name": "Google One",
        "category": "Cloud Storage",
        "website": "https://one.google.com/",
        "cancellation_url": "https://one.google.com/",
    },
    {
        "name": "Twitch",
        "category": "Streaming",
        "website": "https://www.twitch.tv/",
        "cancellation_url": "https://www.twitch.tv/subscriptions",
    },
    {
        "name": "YouTube Premium",
        "category": "Streaming",
        "website": "https://www.youtube.com/premium",
        "cancellation_url": "https://www.youtube.com/paid_memberships",
    },
    {
        "name": "Amazon Prime",
        "category": "Membership",
        "website": "https://www.amazon.com/amazonprime",
        "cancellation_url": "https://www.amazon.com/primecentral",
    },
]


def seed_predefined_providers(apps, schema_editor):
    Provider = apps.get_model("subscriptions", "Provider")

    for provider_data in PREDEFINED_PROVIDERS:
        Provider.objects.update_or_create(
            owner=None,
            name=provider_data["name"],
            defaults={
                "category": provider_data["category"],
                "website": provider_data["website"],
                "cancellation_url": provider_data["cancellation_url"],
            },
        )


def unseed_predefined_providers(apps, schema_editor):
    Provider = apps.get_model("subscriptions", "Provider")
    provider_names = [provider["name"] for provider in PREDEFINED_PROVIDERS]
    Provider.objects.filter(owner__isnull=True, name__in=provider_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_provider_cancellation_url"),
    ]

    operations = [
        migrations.RunPython(seed_predefined_providers, unseed_predefined_providers),
    ]
